version: '3'
services:

  flask:
    build: .
    container_name: flask
    restart: unless-stopped
    command: python run.py
    environment:
      FLASK_APP: run.py
      FLASK_ENV: "production"
      FLASK_DEBUG: "False"
      FLASK_PORT: 5000
      MONGODB_DATABASE: iqvizyondb
      MONGODB_HOSTNAME: mongodb://mongodb/iqvizyondb
      CELERY_RESULT_BACKEND: mongodb://mongodb/iqvizyondb
      CELERY_BROKER_URL: mongodb://mongodb/iqvizyondb
    ports:
      - "5000:5000"
    volumes:
      - appdata:/var/www
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - frontend
      - backend

  celery:
    build: .
    container_name: celery
    restart: unless-stopped
    command: celery -A run worker -B -Q celery -l INFO
    environment:
      FLASK_APP: run.py
      FLASK_ENV: "production"
      FLASK_DEBUG: "False"
      FLASK_PORT: 5000
      MONGODB_DATABASE: iqvizyondb
      MONGODB_HOSTNAME: mongodb://mongodb/iqvizyondb
      CELERY_RESULT_BACKEND: mongodb://mongodb/iqvizyondb
      CELERY_BROKER_URL: mongodb://mongodb/iqvizyondb
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - frontend
      - backend

  mongodb:
    image: mongo:3.6.3
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: iqvizyondb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local